-- -----------------------------------------------------
-- Table CLIENTES
-- -----------------------------------------------------
CREATE TABLE  CLIENTES (
  idCLIENTES INT NOT NULL,
  NOME VARCHAR(45) NULL,
  EMAIL VARCHAR(45) NULL,
  CPF VARCHAR(15) NULL,
  ENDERECO COMPLPETO VARCHAR(60) NULL,
  CEP VARCHAR(10) NULL,
  TELEFONE VARCHAR(15) NULL,
  PRIMARY KEY (idCLIENTES)
  );
 

-- -----------------------------------------------------
-- Table PRODUTOS
-- -----------------------------------------------------
CREATE TABLE  PRODUTOS (
  idPRODUTOS INT NOT NULL,
  DESCRICAO VARCHAR(45) NULL,
  TAMANHO VARCHAR(5) NULL,
  MATERIAL VARCHAR(100) NULL,
  QUANTIDADE VARCHAR(100) NULL,
  CLIENTES_idCLIENTES INT NOT NULL,
  PRIMARY KEY (idPRODUTOS),
  CONSTRAINT fk_PRODUTOS_CLIENTES1
  
  FOREIGN KEY (CLIENTES_idCLIENTES) REFERENCES CLIENTES (idCLIENTES)
  );